version: "3.5"
services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-api
    container_name: node-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
